table dim_followers
	lineageTag: 0c199ee8-1007-42ba-b4b4-65193265b5a0

	column username
		dataType: string
		lineageTag: 680119a1-4cab-49ba-8227-b66455d9a845
		summarizeBy: none
		sourceColumn: username

		annotation SummarizationSetBy = Automatic

	column username_url
		dataType: string
		lineageTag: be647b1e-3d21-45d4-bc67-5d228ac44f50
		summarizeBy: none
		sourceColumn: username_url

		annotation SummarizationSetBy = Automatic

	column first_follow_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a04dc983-b57a-4a74-8342-7f6ebe9e1e7f
		summarizeBy: none
		sourceColumn: first_follow_date

		variation Variation
			isDefault
			relationship: 81ad580d-5e0c-4d05-95ab-ac721059bba1
			defaultHierarchy: LocalDateTable_978ea060-5f28-4a68-a7d0-bdd6115d652e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column last_seen_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6bf70033-48a8-473e-8e9d-f67d8253593c
		summarizeBy: none
		sourceColumn: last_seen_date

		variation Variation
			isDefault
			relationship: d83cfb96-cece-4ed8-8804-896c7cf6fc35
			defaultHierarchy: LocalDateTable_37210f71-30ac-4560-a305-51269c027622.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_followers = m
		mode: import
		source =
				let
				    Source   = fact_followers,     // הטבלת בסיס שלך
				    KeepCols = Table.SelectColumns(Source, {"username", "username_url", "follow_date", "RunDate"}),
				    Grouped  = Table.Group(
				        KeepCols,
				        {"username"},
				        {
				            {"first_follow_date", each List.Min(List.RemoveNulls([follow_date])), type nullable date},
				            {"username_url",      each List.Last(List.RemoveNulls([username_url])),  type text},
				            {"last_seen_date",    each List.Max(List.RemoveNulls([RunDate])), type nullable date}
				        }
				    ),
				    Reorder  = Table.ReorderColumns(Grouped, {"username","username_url","first_follow_date"}),
				    Typed    = Table.TransformColumnTypes(Reorder, {{"username", type text}, {"username_url", type text}, {"first_follow_date", type date}}),
				    #"Removed Duplicates" = Table.Distinct(Typed, {"username"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

