table fact_posts_likers
	lineageTag: ae08ff74-a434-4756-8be5-a4a6635bec52

	measure 'Distinct Likers' = DISTINCTCOUNT( fact_posts_likers[username] )
		formatString: 0
		displayFolder: Likes
		lineageTag: 40de6ee8-ff95-43ee-9d59-d546eec77c45

		changedProperty = IsHidden

	measure 'Total Likes' = COUNTROWS('fact_posts_likers')
		formatString: 0
		displayFolder: Likes
		lineageTag: 23febf70-41aa-4eb5-bfff-9dba0d46e620

		changedProperty = IsHidden

	measure 'Total Engagement' = [Total Likes] + [Total Comments]
		displayFolder: Engagement
		lineageTag: ec18fb81-bd7c-4187-9d95-0ec21e0af6b8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rank by Likes' =
			
			RANKX(
			    ALLSELECTED( 'dim_posts' ),
			    [Total Likes],
			    ,
			    DESC,
			    Dense
			)
		formatString: 0
		displayFolder: Likes
		lineageTag: 77eb10ad-5632-4183-9419-76e32a7433d9

		changedProperty = IsHidden

	measure 'Engagement Rate %' =
			
			VAR _Interactions = [Total Likes] + [Total Comments]
			VAR _Followers = [Total Followers]
			RETURN
			DIVIDE(_Interactions, _Followers, BLANK())
		displayFolder: Engagement
		lineageTag: 359b5a43-1f38-46d1-970c-116e45b9ffa5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gauge Max Value' =
			
			MAX( [Total Likes], [Total Likes LM] ) * 1.2
		displayFolder: Likes
		lineageTag: d7484a40-50a0-4e6e-9457-cea5b7aa4b3c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Max Likes (Record)' = MAXX( 'dim_posts', [Total Likes] )
		formatString: 0
		displayFolder: Likes
		lineageTag: 4d2de86b-1787-477d-a64b-62001e3c58ec

		changedProperty = IsHidden

	measure 'Total Likes LM' = ```
			
			CALCULATE(
			    [Total Likes], 
			    DATEADD('dim_date'[Date], -1, MONTH)
			)
			```
		formatString: 0
		displayFolder: Likes\Time Intelligence
		lineageTag: 5ecb90a3-80c9-424c-a982-8d4055ed041e

		changedProperty = IsHidden

	measure 'Likes MoM %' =
			
			VAR CurrentLikes = [Total Likes]
			VAR PrevLikes = [Total Likes LM]
			RETURN
			DIVIDE(CurrentLikes - PrevLikes, PrevLikes, BLANK())
		displayFolder: Likes\Time Intelligence
		lineageTag: d14736a2-29db-42a5-a111-615a8ac956f2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Likes SMLY' = ```
			
			CALCULATE(
			    [Total Likes], 
			    SAMEPERIODLASTYEAR('dim_date'[Date])
			)
			```
		displayFolder: Likes\Time Intelligence
		lineageTag: 0d412bb4-149a-4165-aafc-9d8df0034c83

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Likes YTD' =
			
			TOTALYTD([Total Likes], 'dim_date'[Date])
		formatString: 0
		displayFolder: Likes\Time Intelligence
		lineageTag: 005004fe-d268-4b44-bea5-457cdf26124a

		changedProperty = IsHidden

	measure 'Total Likes YTD LY' = CALCULATE([Total Likes YTD], SAMEPERIODLASTYEAR('dim_date'[Date]))
		formatString: 0
		displayFolder: Likes\Time Intelligence
		lineageTag: 83c51dc8-9920-4119-8dbc-46856cf42453

		changedProperty = IsHidden

	measure 'Likes Color Logic' = ```
			
			IF(
			    [Total Likes] > [Total Likes SMLY], 
			    "#0F9C66",  
			    "#EA0D1E"  
			)
			```
		displayFolder: Likes
		lineageTag: 33c30846-2512-47da-959c-f8e76975135b

		changedProperty = IsHidden

	measure 'Total Engagement YTD' = TOTALYTD([Total Engagement], 'dim_date'[Date])
		formatString: 0
		displayFolder: Engagement\Time Intelligence
		lineageTag: 7012ccc8-a766-424a-9f80-3f928a5c7c32

		changedProperty = IsHidden

	measure 'Total Engagement LM' = ```
			
			CALCULATE(
			    [Total Engagement], 
			    DATEADD('dim_date'[Date], -1, MONTH)
			)
			```
		formatString: 0
		displayFolder: Engagement\Time Intelligence
		lineageTag: bffcceeb-432b-4de0-9ebe-1d77a8d29349

		changedProperty = IsHidden

	measure 'Engagement MoM %' =
			
			VAR CurrentEng = [Total Engagement]
			VAR PrevEng = [Total Engagement LM]
			RETURN
			DIVIDE(CurrentEng - PrevEng, PrevEng, 0)
		displayFolder: Engagement\Time Intelligence
		lineageTag: 68ef30a1-4560-44e3-aa63-6cd1f18eadb3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Engagement YTD LY' =
			
			CALCULATE([Total Engagement YTD], SAMEPERIODLASTYEAR('dim_date'[Date]))
		formatString: 0
		displayFolder: Engagement\Time Intelligence
		lineageTag: a439f402-992c-4281-9f59-95881a640451

		changedProperty = IsHidden

	measure 'Engagement YTD % Change' =
			
			VAR CurrentVal = [Total Engagement YTD]
			VAR PrevVal = [Total Engagement YTD LY]
			RETURN
			DIVIDE(CurrentVal - PrevVal, PrevVal, BLANK())
		displayFolder: Engagement\Time Intelligence
		lineageTag: 18e57551-1bf9-4715-9df5-4952c12f1b86

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Likes YTD % Change' =
			
			VAR CurrentVal = [Total Likes YTD]
			VAR PrevVal = [Total Likes YTD LY]
			RETURN
			DIVIDE(CurrentVal - PrevVal, PrevVal, BLANK())
		displayFolder: Likes\Time Intelligence
		lineageTag: e40b932c-cd35-4f8a-a0a1-cfc441e1677c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Engagement SMLY' = CALCULATE([Total Engagement], SAMEPERIODLASTYEAR('dim_date'[Date]))
		formatString: 0
		displayFolder: Engagement\Time Intelligence
		lineageTag: 65f18229-aaae-4b9e-9aaa-6871269ba4e1

		changedProperty = IsHidden

	measure 'Engagement LY % Change' =
			
			VAR CurrentVal = [Total Engagement]
			VAR PrevVal = [Total Engagement SMLY]
			RETURN
			IF(ISBLANK(PrevVal) || PrevVal=0, BLANK(), DIVIDE(CurrentVal - PrevVal, PrevVal))
		displayFolder: Engagement\Time Intelligence
		lineageTag: 5c06004c-a8fc-4bed-953a-067dabdeb3f5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Likes LY % Change' =
			
			DIVIDE([Total Likes] - [Total Likes SMLY], [Total Likes SMLY], 0)
		formatString: 0%;-0%;0%
		displayFolder: Likes\Time Intelligence
		lineageTag: c3437e8c-7d3a-4cba-b038-767a79592396

		changedProperty = IsHidden

	measure 'Users Who Did Both' =
			
			CALCULATE(
			    DISTINCTCOUNT('fact_posts_likers'[username]),
			    INTERSECT(
			        VALUES('fact_posts_likers'[username]),
			        VALUES('fact_posts_comments'[username])
			    )
			)
		formatString: 0
		displayFolder: Engagement
		lineageTag: b4efb53b-b66f-442d-a6df-e49944075e11

		changedProperty = IsHidden

	measure 'Average Likes Per Post' =
			
			DIVIDE([Total Likes], [Total Posts], BLANK())
		formatString: 0
		displayFolder: Likes
		lineageTag: 0e12ab8d-3a7c-4c07-860c-e0640aa18a4a

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Total likes in the same 7-day period one week prior
	measure 'Total Likes WoW' =
			
			CALCULATE(
			    [Total Likes],
			    DATEADD('dim_date'[Date], -7, DAY)
			)
		displayFolder: Likes\Time Intelligence
		lineageTag: 8b1bbe06-69e6-4c90-8756-4c8cde64f5ad

	/// Week-over-week growth rate for Likes. Positive = improvement vs. same 7-day window last week.
	measure 'Likes WoW %' =
			
			VAR CurrLikes = [Total Likes]
			VAR PrevLikes = [Total Likes WoW]
			RETURN
			DIVIDE(CurrLikes - PrevLikes, PrevLikes, BLANK())
		formatString: 0.00%
		displayFolder: Likes\Time Intelligence
		lineageTag: fd2322cf-affe-452b-9ad0-ca720aa7df12

	/// Rolling 7-day average of daily likes. Smooths viral spikes to reveal the underlying engagement trend. Place on a line chart with dim_date[Date] as the axis.
	measure 'Likes 7-Day Avg' =
			
			DIVIDE(
			    CALCULATE(
			        [Total Likes],
			        DATESINPERIOD('dim_date'[Date], MAX('dim_date'[Date]), -7, DAY)
			    ),
			    7,
			    BLANK()
			)
		formatString: #,##0.0
		displayFolder: Likes\Time Intelligence
		lineageTag: 94c23545-2469-4200-a064-9ef6988af3f0

	column post_shortcode
		dataType: string
		lineageTag: 20c0bac4-f0d0-491c-afe6-d59af11d84a1
		summarizeBy: none
		sourceColumn: post_shortcode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column username
		dataType: string
		lineageTag: f07e2ecd-fc17-4b5e-93fb-96101c39fc66
		summarizeBy: none
		sourceColumn: username

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RunDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 74ae37b7-a7a8-4e3f-a557-1be82212c5b2
		summarizeBy: none
		sourceColumn: RunDate

		variation Variation
			isDefault
			relationship: 2e0393d7-c860-448b-ada8-1f490a594612
			defaultHierarchy: LocalDateTable_42b880c0-c186-4fe0-95ab-20adc1371f1b.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fact_posts_likers = m
		mode: import
		source =
				let
				    // <<< UPDATE THIS PATH IF NEEDED >>>
				    FolderPath = "C:\Users\Erez\OneDrive - Bar-Ilan University - Students\Desktop\instagram project\data\instagram_media",
				
				    Source       = Folder.Files(FolderPath),
				    KeepLikers   = Table.SelectRows(Source, each [Name] = "batch_likers.csv" and [Extension] = ".csv"),
				
				    // add RunDate from parent folder (YYYY-MM-DD at the end of folder path)
				    WithRunDate  = Table.AddColumn(
				        KeepLikers, "RunDate",
				        each try Date.FromText(Text.End(Text.TrimEnd([Folder Path], "\"), 10)) otherwise null,
				        type date
				    ),
				
				    // read each CSV and normalize column names
				    ReadEach = Table.AddColumn(WithRunDate, "Data", each
				        let
				            raw   = Csv.Document([Content], [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				            hdr   = Table.PromoteHeaders(raw, [PromoteAllScalars=true]),
				            // trim headers and normalize 'url' -> 'username_url' when needed
				            trimH = Table.TransformColumnNames(hdr, Text.Trim),
				            fixH  = if List.Contains(Table.ColumnNames(trimH), "username_url")
				                    then trimH
				                    else Table.RenameColumns(trimH, {{"url","username_url"}}, MissingField.Ignore),
				            typed = Table.TransformColumnTypes(fixH, {
				                        {"post_shortcode", type text},
				                        {"username",      type text},
				                        {"username_url",  type text},
				                        {"media_url",     type text}
				                    }),
				            addRD = Table.AddColumn(typed, "RunDate", (r)=> [RunDate], type date),
				            final = Table.SelectColumns(addRD, {
				                        "post_shortcode","username","username_url","media_url","RunDate"
				                    })
				        in  final
				    ),
				
				    Combined = Table.Combine(ReadEach[Data]),
				
				    // sort so שכל ריצה חדשה למעלה ואז לפי פוסט/יוזר
				    Sorted = Table.Sort(Combined, {
				                {"RunDate", Order.Descending},
				                {"post_shortcode", Order.Ascending},
				                {"username", Order.Ascending}
				            }),
				    #"Changed Type" = Table.TransformColumnTypes(Sorted,{{"RunDate", type date}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"username", "media_url"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Duplicates",{"username_url", "media_url"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

