table 'Select Metric'
	lineageTag: 7e73005c-e289-462d-bd9e-7b45507f2688

	measure 'Dynamic YTD Value' = ```
			
			VAR Selection = SELECTEDVALUE('Select Metric'[Select Metric Order])
			
			RETURN
			SWITCH( Selection,
			    0, [Total Likes YTD],     
			    1, [Total Comments YTD],   
			    2, [Total Engagement YTD], 
			    [Total Likes YTD]          
			)
			```
		formatString: 0
		displayFolder: Dynamic (Switcher)
		lineageTag: dfbe1f53-032c-4370-8fc4-b97145e29a60

	measure 'Dynamic LM Value' = ```
			
			VAR Selection = SELECTEDVALUE('Select Metric'[Select Metric Order])
			
			RETURN
			SWITCH( Selection,
			    0, [Total Likes LM],       
			    1, [Total Comments LM],   
			    2, [Total Engagement LM],  
			    [Total Likes LM]          
			)
			```
		formatString: 0
		displayFolder: Dynamic (Switcher)
		lineageTag: 4b4d9061-714f-4dee-a950-f5426ec204fa

	measure 'Dynamic MoM %' =
			
			VAR Selection = SELECTEDVALUE('Select Metric'[Select Metric Order])
			RETURN
			SWITCH( Selection,
			    0, [Likes MoM %],
			    1, [Comments MoM %],
			    2, [Engagement MoM %],
			    [Likes MoM %]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Dynamic (Switcher)
		lineageTag: e62178c1-e2a4-4c02-85f5-9b1ca5cf5e52

	measure 'Dynamic YTD Target' = ```
			
			VAR Selection = SELECTEDVALUE('Select Metric'[Select Metric Order])
			
			RETURN
			SWITCH( Selection,
			    0, [Total Likes YTD LY],       
			    1, [Total Comments YTD LY],    
			    2, [Total Engagement YTD LY],  
			    [Total Likes YTD LY]          
			)
			```
		formatString: 0
		displayFolder: Dynamic (Switcher)
		lineageTag: 77a101b0-147a-44bf-a4a6-a275e1cb3c92

	measure 'Title YTD' =
			
			MAX('Select Metric'[Select Metric]) & " - YTD Comparison"
		displayFolder: Dynamic (Switcher)\Titles
		lineageTag: da8e4bf4-0d83-4d27-8a30-1bbdb7681042

	measure 'Title LM' =
			
			MAX('Select Metric'[Select Metric]) & " - Last Month Comparison"
		displayFolder: Dynamic (Switcher)\Titles
		lineageTag: ba4ddaaa-1ba7-4673-a01d-201d8d32ed6b

	measure 'Title LY' =
			
			MAX('Select Metric'[Select Metric]) & " - Last Year Comparison"
		displayFolder: Dynamic (Switcher)\Titles
		lineageTag: 0411ea8a-55d0-4dfe-a8c7-f8534110d7dc

	measure 'Dynamic YTD % Change' =
			
			VAR Selection = SELECTEDVALUE('Select Metric'[Select Metric Order])
			RETURN
			SWITCH( Selection,
			    0, [Likes YTD % Change],
			    1, [Comments YTD % Change],
			    2, [Engagement YTD % Change],
			    [Likes YTD % Change]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Dynamic (Switcher)
		lineageTag: 9e808cae-aaaf-4e12-93a6-c68c90990559

	measure 'Dynamic LY Target' =
			
			VAR Selection = SELECTEDVALUE('Select Metric'[Select Metric Order])
			RETURN
			SWITCH( Selection,
			    0, [Total Likes SMLY],
			    1, [Total Comments SMLY],
			    2, [Total Engagement SMLY],
			    [Total Likes SMLY]
			)
		formatString: 0
		displayFolder: Dynamic (Switcher)
		lineageTag: aaf81c59-646f-4337-9f9d-da25f228b94a

	measure 'Dynamic LY % Change' =
			
			VAR Selection = SELECTEDVALUE('Select Metric'[Select Metric Order])
			RETURN
			SWITCH( Selection,
			    0, [Likes LY % Change],
			    1, [Comments LY % Change],
			    2, [Engagement LY % Change],
			    [Likes LY % Change]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Dynamic (Switcher)
		lineageTag: 2c16cd84-4d16-48f3-9e40-e24b6aaae88d

	measure 'Title Distribution' = MAX('Select Metric'[Select Metric]) & " by Post Type"
		displayFolder: Dynamic (Switcher)\Titles
		lineageTag: 3e00424c-7369-43a0-a5ca-19b889abe71f

	measure 'Title Monthly Trend' =
			
			MAX('Select Metric'[Select Metric]) & " - Monthly Trend"
		displayFolder: Dynamic (Switcher)\Titles
		lineageTag: 063c5ce7-1013-4478-81cd-14d5fdaa592d

	column 'Select Metric'
		lineageTag: 642e6edb-3e09-4b98-9f6e-70b6d912f524
		summarizeBy: none
		sourceColumn: [Value1]
		sortByColumn: 'Select Metric Order'

		relatedColumnDetails
			groupByColumn: 'Select Metric Fields'

		annotation SummarizationSetBy = Automatic

	column 'Select Metric Fields'
		lineageTag: 18d438aa-d13f-4d85-865b-80e73466391b
		summarizeBy: none
		sourceColumn: [Value2]
		sortByColumn: 'Select Metric Order'

		extendedProperty ParameterMetadata =
				{
				  "version": 3,
				  "kind": 2
				}

		annotation SummarizationSetBy = Automatic

	column 'Select Metric Order'
		formatString: 0
		lineageTag: 8a845f07-4e2d-41a4-bd76-3e24904e6054
		summarizeBy: sum
		sourceColumn: [Value3]

		annotation SummarizationSetBy = Automatic

	partition 'Select Metric' = calculated
		mode: import
		source =
				{
				    ("Total Likes", NAMEOF('fact_posts_likers'[Total Likes]), 0),
				    ("Total Comments", NAMEOF('fact_posts_comments'[Total Comments]), 1),
				    ("User Engagement Total", NAMEOF('fact_posts_likers'[Total Engagement]), 2)
				}

	annotation PBI_Id = 2d14f6efab6f418a9109bcc66d093fb1

